import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "language": "English",
          "skip": "Skip",
          "product": "product",
          "address": "address",
          "addressVal": "Please enter your address",
          "cont": "Continue",
          "next": "Next",
          "done": "Done",
          "emailAddress": "Email Address",
          "password": "Password",
          "rememberMe": "Remember Me",
          "signIn": "Sign In",
          "signUp": "Sign Up",
          "forgotpass": "Forgot Password?",
          "enterMail": "Please enter your email address",
          "validMail": "Please enter a valid email address",
          "enterPass": "Please enter your password",
          "validPass": "Password must be at least 8 characters long",
          "validPassOneUpper":
              "Password must contain at least one uppercase letter",
          "validPassOneNum": "Password must contain at least one number",
          "validPassOneSpecChar":
              "Password must contain at least one special character",
          "enterPhone": "Please enter your phone number",
          "validPhone": "Phone number should start with 01",
          "validPhoneLen":
              "Invalid phone number, It should consist of 11 numbers.",
          "enterInput": "Please fill this field",
          "enterCode": "Enter Code",
          "codeDesc": "We sent a verification code to",
          "codeResend": "Resend Code",
          "verify": "Verify",
          "errorMes": "Error",
          "okMes": "Ok",
          "wrongCodeMes": "Wrong Code",
          "codeFillMes": "Please fill all code fields",
          "resendDesc": "Resending in",
          "seconds": "seconds",
          "yesMes": "yes",
          "noMes": "no",
          "onBoardingTitle1": "Your favorite Gallery everywhere",
          "onBoardingSubTitle1":
              "Get in contact with multiple trusted furniture galleries",
          "onBoardingTitle2": "We provide latest style products",
          "onBoardingSubTitle2":
              "Our product collection defined in many styles and always updated everyday",
          "onBoardingTitle3": "Contact our galleries",
          "onBoardingSubTitle3":
              "Get in contact with multiple trusted furniture galleries",
          "login": "Login or Sign Up",
          "loginDesc":
              "Please select your preferred method \n to continue setting up your account",
          "continueWithEmail": "Continue with Email",
          "continueWithPhone": "Continue with Phone",
          "continueWithGoogle": "Continue with Google",
          "newToApp": "New to the app?",
          "createNewAccount": "Create a new account",
          "terms": "Terms & Conditions and Privacy Policy Will Apply.",
          "conWithMail": "Get going with email",
          "conWithMailDesc": "Fill in your account information..",
          "conWithPhone": "Get going with phone",
          "conWithPhoneDesc": "Enter your phone number..",
          "gallarySelect": "Do you own furniture gallery?",
          "gallarySelectDesc": "Select Whether you own a gallery..",
          "galleryVal": "Please enter gallery name",
          "galleryVallen": "Gallery name should be greater than 4 characters",
          "gallaryTitle": "Your Gallery",
          "gallaryTitleDesc": "Register your gallery information.",
          "galleryAddressVal":
              "Gallery address should be greater than 6 characters",
          "fileUpload": "Please choose a file",
          "galleryAddressTextval": "Please enter gallery address",
          "galleryName": "Enter Gallery Name",
          "galleryAddress": "Enter Gallery Address",
          "uploadGalleryID": "Upload gallery ID",
          "selectedFile": "Selected file",
          "profilePic": "Profile Picture",
          "selectProfilePic": "Select your profile picture",
          "newAcc": "New Account",
          "newAccDesc": "Register your account information.",
          "confirmPass": "Confirm Password",
          "confirmPassVal": "Please confirm your password",
          "passNoMatch": "Passwords do not match",
          "firstName": "First Name",
          "firstNameVal": "Please enter your first name",
          "lastName": "Last Name",
          "lastNameVal": "Please enter your last name",
          "homeTitle": "Explore What Your Home Needs",
          "categories": "Categories",
          "chairsCat": "Chairs",
          "sofaCat": "Sofas",
          "desksCat": "Desks",
          "stoolsCat": "Stools",
          "seeAll": "See all",
          "discount": "{percent}% off",
          "productBannerTitle": "High quality products started",
          "exploreSec": "Explore",
          "currency": "LE",
          "topGalleries": "Top galleries",
          "roomsSec": "Rooms",
          "roomsSecDesc": "Furniture for every corner in your home",
          "dinRoom": "Dining",
          "bedRoom": "Bed",
          "officeRoom": "Office",
          "homeSearchHint": "Chair, desk, lamp, etc",
          "fav": "Favourites",
          "notif": "Notifications",
          "noFav": "There are no favourites",
          "noNotif": "There are no notifications",
          "chat": "Chat",
          "addProduct": "Add Product",
          "aiDesigns": "AI Designs",
          "profile": "Profile",
          "review": "Reviews",
          "condition": "Condition",
          "productcolor": "Product Color",
          "specifications": "Specifications",
          "smProducts": "Similar Products",
          "smProductsDesc": "products you might be interested in",
          "contactSeller": "Contact the seller",
          "readMore": "Read more",
          "readLess": "Read less",
          "delivery": "Delivery",
          "modify": "Modifiable",
          "negotioate": "Negotiable",
          "productPic": "Product Pictures",
          "productDetails": "Product Details",
          "price": "Price",
          "priceVal": "Please enter a price",
          "description": "Description",
          "descriptionVal": "Please enter a description",
          "selectType": "Select {type} type",
          "wood": "wood",
          "ablakash": "ablakash",
          "cloth": "cloth",
          "type": "type",
          "regular": "regular",
          "zan": "zan",
          "cotton": "cotton",
          "silk": "silk",
          "openCam": "Open Camera & Take Photo",
          "options": "Options",
          "newCond": "New",
          "used": "Used",
          "notSpecified": "Not specified",
          "imageUpVal": "Please add an image",
          "myPoints": "My points",
          "points": "Points",
          "buyMore": "Buy more",
          "subCat": "Sub Category",
          "prompt": "Prompt",
          "promptVal": "Prompt is empty",
          "createDesign": "Create Design",
          "promptDesc": "enter text and click the button to generate image",
          "manufreq": "Manufacture Requests",
          "buyPoints": "Buy Points",
          "contactUs": "Contact Us",
          "logOut": "Log Out",
          "downloadImage": "Download Image",
          "wrongPassword": "Wrong Password",
          "resetPassword": "Reset Password",
          "fillNewPassword": "Fill in your new password",
          "selectLan": "Select Language",
          "productName": "Product name",
          "and": "and",
          "viewAll": "View all",
          "submit": "Submit",
          "appName": "Furniture Store",
          "tContinue": "Continue",
          "favourites": "Favourites",
          "currencySign": "LE",
          "noFavourites": "No favourites",
          "myAccount": "My Account",
          "appSettings": "App settings",
          "accountSettings": "Account settings",
          "languageDesc": "Set app language",
          "myAdresses": "My Addresses",
          "myAdressesDesc": "Set shopping delivery addresses",
          "manefactureReq": "Manufacture Requests",
          "manefactureReqDesc": "See what others have created",
          "buyPointsDesc": "Get more creative design points",
          "darkMode": "Dark Mode",
          "darkModeDesc": "Set the app theme to dark-mode",
          "email": "E-Mail",
          "newPassword": "New Password",
          "username": "Username",
          "phoneNo": "Phone Number",
          "forgetPassword": "Forget Password?",
          "createAccount": "Create Account",
          "orSignInWith": "or sign in with",
          "orSignUpWith": "or sign up with",
          "iAgreeTo": "I agree to",
          "privacyPolicy": "Privacy Policy",
          "termsOfUse": "Terms of use",
          "verificationCode": "verificationCode",
          "resendEmail": "Resend Email",
          "resendEmailIn": "Resend email in",
          "confirmPassword": "Confirm Password",
          "congrats": "Congratulations",
          "logout": "Log out",
          "loginHeader": "Login in or Sign up",
          "loginSubHeader":
              "Please select your preferred method \n to continue setting up your account",
          "continueWithPhoneTitle": "Get going with your phone number",
          "continueWithPhoneSubTitle": "Enter your phone number",
          "accountCreationConfirmed":
              'Your account has been created successfully',
          "loginTitle": "Welcome back,",
          "loginSubTitle":
              "Discover Limitless Choices and Unmatched Convenience.",
          "signupTitle": "Let’s create your account",
          "forgetPasswordTitle": "Forget password",
          "forgetPasswordSubTitle":
              "Don’t worry sometimes people can forget too, enter your email and we will send you a password reset link.",
          "changeYourPasswordTitle": "Password Reset Email Sent",
          "changeYourEmailTitle": "Email Sent",
          "changeYourEmailSubTitle":
              "Please check your inbox and verify your email.",
          "changeYourPasswordSubTitle":
              "Your Account Security is Our Priority! We've Sent You a Secure Link to Safely Change Your Password and Keep Your Account Protected.",
          "confirmEmail": "Verify your email address!",
          "confirmEmailSubTitle":
              "Congratulations! Your Account Awaits: Verify Your Email to Start Shopping and Experience a World of Unrivaled Deals and Personalized Offers.",
          "emailNotReceivedMessage":
              "Didn’t get the email? Check your junk/spam or resend it.",
          "yourAccountCreatedTitle": "Your account successfully created!",
          "yourAccountCreatedSubTitle":
              "Welcome to Your Ultimate Shopping Destination: Your Account is Created, Unleash the Joy of Seamless Online Shopping!",
          "homeSearchBarHint": "Chair, desk, lamp, etc",
          "chairsCartegory": "Chairs",
          "sofaCartegory": "Sofas",
          "desksCartegory": "Desks",
          "popularProducts": "Popular Products",
          "homeAppbarTitle": "Explore What Your Home Needs",
        },
        'ar_SA': {
          "language": "العربية",
          "skip": "تخطي",
          "next": "التالي",
          "done": "تم",
          "emailAddress": "عنوان البريد الإلكتروني",
          "password": "كلمة المرور",
          "rememberMe": "تذكرني",
          "signIn": "تسجيل الدخول",
          "signUp": "سجل",
          "forgotpass": "هل نسيت كلمة المرور؟",
          "enterMail": "الرجاء إدخال عنوان بريدك الإلكتروني",
          "validMail": "الرجاء إدخال عنوان بريد إلكتروني صالح",
          "enterPass": "الرجاء إدخال كلمة المرور الخاصة بك",
          "validPass": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
          "enterPhone": "الرجاء إدخال رقم هاتفك",
          "validPhone": "يجب أن يبدأ رقم الهاتف بـ 01",
          "validPhoneLen": "رقم هاتف غير صالح، يجب أن يتكون من 11 رقمًا",
          "enterCode": "أدخل الكود",
          "codeDesc": "لقد قمنا بإرسال رمز التحقق إلى",
          "codeResend": "إعادة إرسال الكود",
          "verify": "التحقق",
          "errorMes": "خطأ",
          "okMes": "حسناً",
          "wrongCodeMes": "رمز خاطئ",
          "codeFillMes": "يرجى ملء جميع حقول الكود",
          "resendDesc": "إعادة الإرسال في",
          "seconds": "ثواني",
          "yesMes": "نعم",
          "noMes": "لا",
          "productName": "اسم المنتج",
          "onBoardingTitle1": "معرضك المفضل في كل مكان",
          "onBoardingSubTitle1": "تواصل مع العديد من معارض الأثاث الموثوقة",
          "onBoardingTitle2": "نحن نقدم منتجات بأحدث الأنماط",
          "onBoardingSubTitle2":
              "تم تحديد مجموعتنا من المنتجات بأنماط متعددة وتحديثها دائمًا كل يوم",
          "onBoardingTitle3": "تواصل مع معارضنا",
          "onBoardingSubTitle3": "تواصل مع العديد من معارض الأثاث الموثوقة",
          "login": "تسجيل الدخول أو التسجيل",
          "loginDesc":
              "الرجاء اختيار الطريقة المفضلة لديك \n لمتابعة إعداد حسابك",
          "continueWithEmail": "المتابعة بالبريد الإلكتروني",
          "continueWithPhone": "المتابعة برقم الهاتف",
          "continueWithGoogle": "المتابعة مع جوجل",
          "newToApp": "جديد في التطبيق؟",
          "createNewAccount": "إنشاء حساب جديد",
          "terms": "ستنطبق الشروط والأحكام وسياسة الخصوصية.",
          "conWithMail": "البدء بالبريد الإلكتروني",
          "conWithMailDesc": "املأ معلومات حسابك..",
          "conWithPhone": "البدء برقم الهاتف",
          "conWithPhoneDesc": "أدخل رقم هاتفك..",
          "validPassOneUpper":
              "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
          "validPassOneNum": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
          "validPassOneSpecChar":
              "يجب أن تحتوي كلمة المرور على حرف خاص واحد على الأقل",
          "gallarySelect": "هل تمتلك معرضًا للأثاث؟",
          "gallarySelectDesc": "حدد ما إذا كنت تمتلك معرضًا..",
          "galleryVal": "الرجاء إدخال اسم المعرض",
          "galleryVallen": "يجب أن يكون اسم المعرض أكبر من 4 أحرف",
          "gallaryTitle": "معرضك",
          "gallaryTitleDesc": "سجل معلومات معرضك.",
          "galleryAddressVal": "يجب أن يكون عنوان المعرض أكبر من 6 أحرف",
          "fileUpload": "الرجاء اختيار ملف",
          "galleryAddressTextval": "الرجاء إدخال عنوان المعرض",
          "galleryName": "أدخل اسم المعرض",
          "galleryAddress": "أدخل عنوان المعرض",
          "uploadGalleryID": "تحميل معرض الهوية",
          "selectedFile": "الملف المحدد",
          "profilePic": "صورة الملف الشخصي",
          "selectProfilePic": "حدد صورة ملفك الشخصي",
          "newAcc": "حساب جديد",
          "newAccDesc": "سجل معلومات حسابك.",
          "confirmPass": "تأكيد كلمة المرور",
          "confirmPassVal": "الرجاء تأكيد كلمة المرور الخاصة بك",
          "passNoMatch": "كلمات المرور غير متطابقة",
          "firstName": "الاسم الأول",
          "firstNameVal": "الرجاء إدخال الاسم الأول الخاص بك",
          "lastName": "اسم العائلة",
          "lastNameVal": "الرجاء إدخال اسم العائلة الخاص بك",
          "homeTitle": "استكشاف احتياجات منزلك",
          "categories": "الفئات",
          "chairsCat": "كراسي",
          "sofaCat": "أرائك",
          "desksCat": "مكاتب",
          "stoolsCat": "مقاعد",
          "seeAll": "عرض الكل",
          "discount": "خصم {percent}%",
          "productBannerTitle": "بدأت المنتجات عالية الجودة",
          "exploreSec": "استكشاف",
          "currency": "ج.م",
          "topGalleries": "أفضل المعارض",
          "roomsSec": "الغرف",
          "roomsSecDesc": "الأثاث لكل زاوية في منزلك",
          "dinRoom": "طعام",
          "bedRoom": "سرير",
          "officeRoom": "مكتب",
          "enterInput": "برجاء ملئ هذه الخانة",
          "homeSearchHint": "كرسي، مكتب، لمبة، إلخ",
          "fav": "المفضلة",
          "notif": "الإشعارات",
          "noFav": "لا يوجد مفضلة",
          "noNotif": "لا يوجد إشعارات",
          "chat": "الدردشة",
          "addProduct": "أضف منتج",
          "aiDesigns": "تصاميم الذكاء الاصطناعي",
          "profile": "الملف الشخصي",
          "review": "التقييمات",
          "condition": "الحالة",
          "productcolor": "لون المنتج",
          "specifications": "المواصفات",
          "smProducts": "منتجات مماثلة",
          "smProductsDesc": "المنتجات التي قد تهتم بها",
          "contactSeller": "الاتصال بالبائع",
          "readMore": "قراءة المزيد",
          "readLess": "قراءة أقل",
          "delivery": "التوصيل",
          "modify": "قابل للتعديل",
          "negotioate": "قابل للتفاوض",
          "productPic": "صور المنتج",
          "productDetails": "تفاصيل المنتج",
          "price": "السعر",
          "priceVal": "الرجاء إدخال السعر",
          "description": "وصف",
          "descriptionVal": "الرجاء إدخال وصف",
          "selectType": "حدد نوع {type}",
          "wood": "خشب",
          "ablakash": "أبلاكاش",
          "cloth": "قماش",
          "type": "نوع",
          "regular": "عادي",
          "zan": "زان",
          "cotton": "قطن",
          "silk": "حرير",
          "openCam": "افتح الكاميرا والتقط صورة",
          "options": "خيارات",
          "newCond": "جديد",
          "used": "مستعمل",
          "notSpecified": "غير محدد",
          "imageUpVal": "يرجى إضافة صورة",
          "myPoints": "نقاطي",
          "points": "نقاط",
          "buyMore": "شراء المزيد",
          "subCat": "فئة فرعية",
          "prompt": "الامر",
          "promptVal": "برجاء كتابة امر",
          "createDesign": "إنشاء تصميم",
          "promptDesc": "أدخل النص وانقر على الزر لتوليد الصورة",
          "manufreq": "طلبات التصنيع",
          "buyPoints": "شراء النقاط",
          "contactUs": "اتصل بنا",
          "logOut": "تسجيل الخروج",
          "downloadImage": "تحميل الصورة",
          "wrongPassword": "كلمة المرور خاطئة",
          "resetPassword": "إعادة تعيين كلمة المرور",
          "fillNewPassword": "املأ كلمة المرور الجديدة الخاصة بك",
          "selectLan": "اختر اللغة",
          "and": "و",
          "currencySign": "جنيه",
          "submit": "إرسال",
          "appName": "متجر الأثاث",
          "tContinue": "متابعة",
          "favourites": "المفضلة",
          "noFavourites": "لا يوجد مفضلة",
          "myAccount": "حسابي",
          "appSettings": "إعدادات التطبيق",
          "accountSettings": "إعدادات الحساب",
          "languageDesc": "تحديد لغة التطبيق",
          "myAdresses": "عناويني",
          "myAdressesDesc": "تعيين عناوين التوصيل",
          "manefactureReq": "طلبات التصنيع",
          "manefactureReqDesc": "رؤية ما قام به الآخرون",
          "buyPointsDesc": "الحصول على نقاط تصميم إبداعية أكثر",
          "darkMode": "الوضع الداكن",
          "darkModeDesc": "تعيين ثيم التطبيق للوضع الداكن",
          "email": "البريد الإلكتروني",
          "newPassword": "كلمة المرور الجديدة",
          "username": "اسم المستخدم",
          "phoneNo": "رقم الهاتف",
          "forgetPassword": "نسيت كلمة المرور؟",
          "address": "العنوان",
          "createAccount": "إنشاء حساب",
          "orSignInWith": "أو تسجيل الدخول باستخدام",
          "orSignUpWith": "أو التسجيل باستخدام",
          "iAgreeTo": "أوافق على",
          "privacyPolicy": "سياسة الخصوصية",
          "termsOfUse": "شروط الاستخدام",
          "verificationCode": "رمز التحقق",
          "resendEmail": "إعادة إرسال البريد الإلكتروني",
          "resendEmailIn": "إعادة إرسال البريد الإلكتروني في",
          "confirmPassword": "تأكيد كلمة المرور",
          "congrats": "تهانينا",
          "logout": "تسجيل الخروج",
          "loginHeader": "تسجيل الدخول أو التسجيل",
          "loginSubHeader":
              "يرجى تحديد الطريقة المفضلة لديك \n لمتابعة إعداد حسابك",
          "continueWithPhoneTitle": "ابدأ باستخدام رقم هاتفك",
          "continueWithPhoneSubTitle": "أدخل رقم هاتفك",
          "accountCreationConfirmed": 'تم إنشاء حسابك بنجاح',
          "loginTitle": "مرحبًا مرة أخرى،",
          "loginSubTitle": "اكتشف الخيارات اللامحدودة والراحة غير المسبوقة.",
          "signupTitle": "لنقم بإنشاء حسابك",
          "forgetPasswordTitle": "نسيت كلمة المرور",
          "forgetPasswordSubTitle":
              "لا تقلق أحيانًا يمكن للأشخاص نسيان ذلك أيضًا، أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.",
          "changeYourPasswordTitle":
              "تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور",
          "changeYourEmailTitle": "تم إرسال البريد الإلكتروني",
          "changeYourEmailSubTitle":
              "يرجى التحقق من صندوق الوارد الخاص بك وتأكيد بريدك الإلكتروني.",
          "changeYourPasswordSubTitle":
              "أمان حسابك هو أولويتنا! لقد أرسلنا لك رابطًا آمنًا لتغيير كلمة المرور الخاصة بك والحفاظ على حسابك محميًا.",
          "confirmEmail": "تحقق من عنوان بريدك الإلكتروني!",
          "confirmEmailSubTitle":
              "تهانينا! حسابك في انتظار التحقق: قم بالتحقق من بريدك الإلكتروني لبدء التسوق وتجربة عالم من العروض غير المسبوقة والعروض المخصصة.",
          "emailNotReceivedMessage":
              "لم تتلقى البريد الإلكتروني؟ تحقق من البريد العشوائي / البريد غير المرغوب فيه أو أعد إرساله.",
          "yourAccountCreatedTitle": "تم إنشاء حسابك بنجاح!",
          "yourAccountCreatedSubTitle":
              "مرحبًا بك في وجهتك النهائية للتسوق: تم إنشاء حسابك، افتح باب التسوق السلس عبر الإنترنت!",
          "homeSearchBarHint": "كرسي، مكتب، لمبة، إلخ",
          "chairsCartegory": "كراسي",
          "sofaCartegory": "صوفا",
          "desksCartegory": "مكاتب",
          "popularProducts": "المنتجات الشهيرة",
          "homeAppbarTitle": "استكشاف احتياجات منزلك",
          "viewAll": "عرض الكل",
        },
      };
}
