name: decordash
description: "Furniture store mobile app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #--------------- PACKAGES ------------------#

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.9
  firebase_app_check: ^0.2.1+17

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1

  # Utility Packages
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  fast_color_picker: ^0.1.1
  stability_image_generation: ^0.0.4
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  logger: ^2.1.0
  shimmer: ^3.0.0

  http: any
  path_provider: any
  uuid: any
  flutter_otp_text_field: ^1.1.2+1
  intl_phone_number_input: ^0.7.4
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/categories/
    - assets/images/content/
    - assets/logos/
    - assets/animations/
    - assets/images/products/beds/
    - assets/images/products/chairs/
    - assets/images/products/sofas/
    - assets/images/products/tables/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
