// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV5QxGvGru16fYuSsvhq8oC0L6ao8mts8',
    appId: '1:129714025607:android:08cce13e8b2f5ddf3f3422',
    messagingSenderId: '129714025607',
    projectId: 'decordash-6e368',
    storageBucket: 'decordash-6e368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXJjOOFvgk0PkoLxEKSTMmFSip4mJ-uo',
    appId: '1:129714025607:ios:fa9bfc42682111d03f3422',
    messagingSenderId: '129714025607',
    projectId: 'decordash-6e368',
    storageBucket: 'decordash-6e368.appspot.com',
    androidClientId: '129714025607-34ja8tfcd8lfrb3a6t9lc7hka03cj79l.apps.googleusercontent.com',
    iosClientId: '129714025607-pvjjnjq5l0bp18vlc83pohv85llhuhiu.apps.googleusercontent.com',
    iosBundleId: 'com.decordash.decordash',
  );
}
