// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vLufUqCGVKj03AeGZ-LAGjkeaeoN-WM',
    appId: '1:323718755688:android:04e6d0ec19494f3dabd2dd',
    messagingSenderId: '323718755688',
    projectId: 'decordashapp',
    storageBucket: 'decordashapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDtl1mU6DpRV12B1ym0zRgwii6TtGCECI',
    appId: '1:323718755688:ios:93bb6a961d793602abd2dd',
    messagingSenderId: '323718755688',
    projectId: 'decordashapp',
    storageBucket: 'decordashapp.appspot.com',
    androidClientId: '323718755688-ig40vhp62nl5ck8gda69226bd5oafpr9.apps.googleusercontent.com',
    iosClientId: '323718755688-is5ic65d33tsprvjl790einoh5spgqqa.apps.googleusercontent.com',
    iosBundleId: 'com.decordash.decordash',
  );

}