// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxE68vGmR0q3nlC6fM1TP90oLo1dXn30s',
    appId: '1:163403932625:android:c3a743ffa7da13c5b676f0',
    messagingSenderId: '163403932625',
    projectId: 'decoredashplatform',
    storageBucket: 'decoredashplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF6kQOO6Wdaw_addXgc6BU4Bj_hrfKa_o',
    appId: '1:163403932625:ios:27bad90a2c9bd357b676f0',
    messagingSenderId: '163403932625',
    projectId: 'decoredashplatform',
    storageBucket: 'decoredashplatform.appspot.com',
    androidClientId: '163403932625-4umo7lk0lmdh95rv1k0e9esaukip6oh1.apps.googleusercontent.com',
    iosClientId: '163403932625-hjq2o7l76i5p3kgv44bfs90ejm9tvsb5.apps.googleusercontent.com',
    iosBundleId: 'com.decordashstore.decordashstore',
  );

}