import 'package:decordash/utils/constants/colors.dart';
import 'package:flutter/material.dart';

ColorScheme lightColorScheme = const ColorScheme(
  brightness: Brightness.light,
  primary: TColors.primary,
  onPrimary: TColors.white,
  primaryContainer: TColors.lightContainer,
  onPrimaryContainer: TColors.black,
  secondary: Color(0xFF0056D0),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFF9F9F9),
  onSecondaryContainer: Color(0xFF001847),
  tertiary: Color(0xFF005AC4),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFD8E2FF),
  onTertiaryContainer: Color(0xFF001A42),
  error: TColors.error,
  errorContainer: Color(0xFFFFDAD6),
  onError: TColors.white,
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFF8FDFF),
  onSurface: Color(0xFF001F25),
  surfaceContainerHighest: Color(0xFFE1E2EC),
  onSurfaceVariant: Color(0xFF44474F),
  outline: Color(0xFF74777F),
  onInverseSurface: Color(0xFFD6F6FF),
  inverseSurface: Color(0xFF00363F),
  inversePrimary: Color(0xFFADC6FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF005BC1),
  outlineVariant: Color(0xFFC4C6D0),
  scrim: Color(0xFF000000),
);

ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: TColors.primary,
  onPrimary: TColors.black,
  primaryContainer: TColors.darkContainer,
  onPrimaryContainer: TColors.black,
  secondary: const Color(0xFFB1C5FF),
  onSecondary: const Color(0xFF002C72),
  secondaryContainer: const Color(0xFF0040A0),
  onSecondaryContainer: const Color(0xFFDAE2FF),
  tertiary: const Color(0xFFAEC6FF),
  onTertiary: const Color(0xFF002E6B),
  tertiaryContainer: const Color(0xFF004396),
  onTertiaryContainer: const Color(0xFFD8E2FF),
  error: TColors.error,
  errorContainer: const Color(0xFF93000A),
  onError: TColors.white,
  onErrorContainer: const Color(0xFFFFDAD6),
  surface: const Color(0xFF001F25),
  onSurface: const Color(0xFFA6EEFF),
  surfaceContainerHighest: const Color(0xFF44474F),
  onSurfaceVariant: const Color(0xFFC4C6D0),
  outline: const Color(0xFF8E9099),
  onInverseSurface: const Color(0xFF001F25),
  inverseSurface: const Color(0xFFA6EEFF),
  inversePrimary: const Color(0xFF005BC1),
  shadow: const Color(0xFF000000),
  surfaceTint: const Color(0xFFADC6FF),
  outlineVariant: const Color(0xFF44474F),
  scrim: const Color(0xFF000000),
);
